version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - /tmp/runbuild/run_buildstep.sh 'build'
  post_build:
    commands:
      - /tmp/runbuild/run_buildstep.sh 'post_build'