version: 0.1

phases:
  install:
    commands:
      - if [ -z $BUILD_KEY ]; then exit 1; fi
      - add-apt-repository ppa:ubuntu-toolchain-r/test
      - apt-get update
      - apt-get upgrade libstdc++6
      - npm install
  build:
    commands:
      - node run_single.js $BUILD_KEY $BUILD_SERIALISER