version: 0.1

phases:
  install:
    commands:
      - if [ -z $BUILD_KEY ]; then exit 1; fi
      - apt-get install libstdc++6
      - npm install
  build:
    commands:
      - node run_single.js $BUILD_KEY $BUILD_SERIALISER