version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - node run_single.js $BUILD_KEY
  post_build:
    commands:
      - /tmp/runbuild/run_buildstep.sh 'post_build'